version: '3.0'

services:

  nginx:
    image: nginx
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./order/OrderManager/public/:/var/www/html/public/
    ports:
      - 80:80

  php:
    build:
      context: ./docker/php
    depends_on:
      - db
    volumes:
      - ./order/OrderManager/:/var/www/html/

  db:
    image: postgres
    restart: always
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
     image: adminer
     restart: always
     depends_on:
       - db
     ports:
       - 8080:8080
  redis:
    image: redis
    depends_on:
      - php

